# Generated by Django 2.1.3 on 2018-12-01 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='available',
            name='group',
            field=models.CharField(default='index', max_length=100),
            preserve_default=False,
        ),
    ]
